# --- TASK 3: CONFIGURAZIONE UPSTREAM PER BLUE/GREEN ---
# Per fare lo switch a Green: commenta la riga di blue e decommenta quella di green.
upstream sio_backend_servers {
    server sio-backend-blue:3000;
    #server sio-backend-green:3000;
}

# AMBIENTE PROD
server {
    listen 80;
    server_name localhost;
    
    location / {
        proxy_pass http://fe-prod:80;
    }
    
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_servers;
    }
}

# AMBIENTE TEST
server {
    listen 8080;
    
    location / {
        proxy_pass http://fe-test:80;
    }
    
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_servers;
    }
}

# AMBIENTE SVI
server {
    listen 8999;
    
    location / {
        proxy_pass http://fe-sio:80;
    }
    
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_servers;
    }
}